---
driver_plugin: vagrant
provisioner: chef_zero

platforms:
- name: centos-6.4_chef-11.4.4
  driver_config:
    box: opscode-centos-6.4_chef-11.4.4
    box_url:  https://opscode-vm.s3.amazonaws.com/vagrant/opscode_centos-6.4_chef-11.4.4.box
- name: ubuntu-12.04_chef-11.4.4
  driver_config:
    box: opscode-ubuntu-12.04_chef-11.4.4
    box_url: https://opscode-vm.s3.amazonaws.com/vagrant/opscode_ubuntu-12.04_chef-11.4.4.box

suites:
- name: default
  run_list:
    - recipe[ktc-testing]
    - recipe[etcd::compile_time]
    - recipe[ktc-monitor::client]
    - recipe[ktc-database]
    - recipe[ktc-messaging]
    - recipe[ktc-memcached]
    - recipe[ktc-identity]
    - recipe[ktc-block-storage]
    - recipe[ktc-block-storage::volume]
  attributes:
    etcd:
      args: '-c 127.0.0.1:4001 -s 127.0.0.1:7001 -f'
      servers:
        - 127.0.0.1
    ha_disabled: true
    mysql:
      allow_remote_root: true
      root_network_acl: '%'
      server_debian_password: 'debian'
      server_root_password: 'root'
      server_repl_password: 'repl'
    openstack:
      developer_mode: true
      block-storage:
        enabled_backends:
        nexenta:
          nfs_shares:
          - server_ip: '10.100.0.21'
            mount_point: '/volumes/ipc-preprod-pod1-zpool0/cinder1'
            management_url: 'http://admin:nexenta@10.100.0.21:2000/'
          - server_ip: '10.100.0.22'
            mount_point: '/volumes/ipc-preprod-pod2-zpool0/cinder1'
            management_url: 'http://admin:nexenta@10.100.0.22:2000/'
    authorization:
      sudo:
        include_sudoers_d: true
        users:
          - vagrant
        passwordless: true

clusters:
  default:
    - default
