#!/bin/bash

crm configure show | grep tid | while IFS= read -r LINE_LAW
do
        tid_str=$(echo $LINE_LAW | cut -d' ' -f 3)
        tid_str_trimmed=${tid_str#tid=}

        tid=${tid_str_trimmed:1:-1}
        echo $tid
done

